### PR TITLE
* Added bloxberg to # 0005: Node Hardware Requirements ## Examples & …

### PR DESCRIPTION
**Pull request by iosifpeterfi**
…Best Practices

### CODE REVIEW

**Comment by iosifpeterfi** [comment]
Please review for approval.

**Comment by iosifpeterfi** [comment]
Please review for approval.

**Comment by fflush** [comment]
According to the guidelines, every PR should contain an RFC. I have therefore opened it as a separate PR. Therefore RFC 0011 would have to be removed here. The adaptations to RFC 0005 are good and can be adopted from my point of view after the commit has been adapted.

**Review by fflush — CHANGES_REQUESTED** [review]
Should be removed. 1 RFC per PR

**Comment by iosifpeterfi** [comment]
I agree. Github somehow merged the PR requests.
I will create a new PR after this first one gets approved.

**Comment by iosifpeterfi** [comment]
I think this one is ready for merging. I removed rfc-0011 and I see David already created a PR for rfc-0011-hardware-monitoring

**Review by fflush — APPROVED** [review]
Works out fine for me

**Review by kiview — APPROVED** [review]
Great, LGTM!

**Pull request merged**
